@schema=https
@hostname=localhost
@port=7179

### Get all cities
GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities

### Create a Point of Interest
# @name createpoi
POST {{schema}}://{{hostname}}:{{port}}/api/v2/cities/1/pointsofinterest
Accept: application/json
Content-Type: application/json

{
    "name": "A name for testing",
    "description": "A description for testing"
}

### Use the created Point of Interest ID
@poiid = {{createpoi.response.body.id}}
GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities/1/pointsofinterest/{{poiid}}
Accept: application/json